### PR TITLE
port change to 3000

### PR DESCRIPTION
**Pull request by rororoisme**
name：劉若瀅
discord id ：rororo

### CODE REVIEW

**Comment by cwpeng** [comment]
Add protection rule to your `main` branch.

**Comment by rororoisme** [comment]
Already add protection rule to main branch at 8/29 am8:00.
Should I need to push again?

**Comment by rororoisme** [comment]
Add protection rule to `main` branch at 8/29 am8:00.

**Review by cwpeng — APPROVED** [review]
ok.

try to figure out how protection rule works for you.

**Pull request merged**
