### PR TITLE
week2 1st

### PR DESCRIPTION
**Pull request by rororoisme**
姓名：劉若瀅
http://44.207.81.80:3000/

麻煩老師幫我檢查第二週的任務，謝謝！

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code will load the same page multiple times if we scroll down and up quickly.
2. Font size, weight should align with design.
3. There should have some spacing between text and border in attraction box.
4. Arrows should have circle borders.
5. Edge of content should align with each other.
6. Layout in some middle size devices are hard to accept.


未命名-8

**Comment by rororoisme** [comment]
感謝老師的提點，沒有注意到切版的細節，
上傳修改後的第二版本，再麻煩老師有空的時候幫我檢查，謝謝

http://44.207.81.80:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Font weight should align with design.
2. Edge of content should align with each other.
3. There should have 2 pages if we search 北.

**Comment by rororoisme** [comment]
這是修正後的任務，再麻煩老師幫我檢查，謝謝！

http://44.207.81.80:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Edge of content should align with each other.
2. Your code will load pages endlessly even if there is no data there. We should stop loading next page when we meet the last page.

**Comment by rororoisme** [comment]
這是修正後的任務，
再麻煩老師幫我檢查，非常感謝！
http://44.207.81.80:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
