### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rororoisme**
http://44.207.81.80:3000/api/attractions?page=0
http://44.207.81.80:3000/api/attractions?page=1&keyword=%E6%96%B0%E5%8C%97%E6%8A%95

http://44.207.81.80:3000/api/attraction/10
http://44.207.81.80:3000/api/attraction/-1
http://44.207.81.80:3000/api/attraction/%e2e35

http://44.207.81.80:3000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. http://44.207.81.80:3000/api/attractions?page=0 dost not work properly.
2. Based on API document, page parameter should start from 0.

Fix issues and re-request review.

**Comment by rororoisme** [comment]
update api/attractions page=0&keyword

http://44.207.81.80:3000/api/attractions?page=0
http://44.207.81.80:3000/api/attractions?page=1&keyword=%E6%96%B0%E5%8C%97%E6%8A%95

http://44.207.81.80:3000/api/attraction/10
http://44.207.81.80:3000/api/attraction/-1
http://44.207.81.80:3000/api/attraction/%e2e35

http://44.207.81.80:3000/api/mrts

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Always use second parameter of execute method to integrate variable into SQL query for preventing SQL injection.

Re-request review after you fixed it.

**Comment by rororoisme** [comment]
Update sql query string.

http://44.207.81.80:3000/api/attractions?page=0
http://44.207.81.80:3000/api/attractions?page=1&keyword=%E6%96%B0%E5%8C%97%E6%8A%95

http://44.207.81.80:3000/api/attraction/10
http://44.207.81.80:3000/api/attraction/-1
http://44.207.81.80:3000/api/attraction/%e2e35

http://44.207.81.80:3000/api/mrts

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
